/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcial;

import javax.swing.table.DefaultTableModel;
import Modelo.Comida;
import DAO.DaoComida;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Andrés
 */
public class AdministrarCategorias extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarCategorias
     */
    public AdministrarCategorias() {
        initComponents();
        setLocationRelativeTo(null);
        btnAgregarCom.setEnabled(false);
        cargarComida();
    }
    public void validarCampo(){
        String categoria = TextoNuevaComida.getText();
        if(!categoria.equals("")){
            btnAgregarCom.setEnabled(true);
        }
        else{
            btnAgregarCom.setEnabled(false);
        }
    }
    
    
    public void Limpiar(){
        TextoNuevaComida.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaComida = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelAgregarCat = new javax.swing.JPanel();
        LabelTituloCategoriasAgregar = new javax.swing.JLabel();
        TextoNuevaComida = new javax.swing.JTextField();
        LabelAgregar = new javax.swing.JLabel();
        btnAgregarCom = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        PanelEliminar = new javax.swing.JPanel();
        LabelTituloCategorias5 = new javax.swing.JLabel();
        jComboBoxComida = new javax.swing.JComboBox<>();
        btnSeleComida = new javax.swing.JButton();
        LabelEliminar = new javax.swing.JLabel();
        Background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/category.png"))); // NOI18N
        jLabel2.setText("Administrar Pedido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/exit.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, 33));

        TablaComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaComida.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(TablaComida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 370, 250));

        PanelAgregarCat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTituloCategoriasAgregar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LabelTituloCategoriasAgregar.setForeground(new java.awt.Color(255, 255, 255));
        LabelTituloCategoriasAgregar.setText("Agregar");
        PanelAgregarCat.add(LabelTituloCategoriasAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        TextoNuevaComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNuevaComidaActionPerformed(evt);
            }
        });
        TextoNuevaComida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextoNuevaComidaKeyReleased(evt);
            }
        });
        PanelAgregarCat.add(TextoNuevaComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 260, -1));

        LabelAgregar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LabelAgregar.setForeground(new java.awt.Color(255, 255, 255));
        LabelAgregar.setText("Crear Nueva Comida");
        PanelAgregarCat.add(LabelAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        btnAgregarCom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/save.png"))); // NOI18N
        btnAgregarCom.setText("Agregar");
        btnAgregarCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComActionPerformed(evt);
            }
        });
        PanelAgregarCat.add(btnAgregarCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/clear.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        PanelAgregarCat.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home-background-image.png"))); // NOI18N
        Background.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BackgroundComponentShown(evt);
            }
        });
        PanelAgregarCat.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 410));

        jTabbedPane1.addTab("Agregar", PanelAgregarCat);

        PanelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTituloCategorias5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LabelTituloCategorias5.setForeground(new java.awt.Color(255, 255, 255));
        LabelTituloCategorias5.setText("Seleccionar");
        PanelEliminar.add(LabelTituloCategorias5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jComboBoxComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxComidaActionPerformed(evt);
            }
        });
        PanelEliminar.add(jComboBoxComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 160, -1));

        btnSeleComida.setText("Seleccionar");
        btnSeleComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleComidaActionPerformed(evt);
            }
        });
        PanelEliminar.add(btnSeleComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        LabelEliminar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        LabelEliminar.setForeground(new java.awt.Color(255, 255, 255));
        LabelEliminar.setText("Seleccionar Comida");
        PanelEliminar.add(LabelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home-background-image.png"))); // NOI18N
        PanelEliminar.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 410));

        jTabbedPane1.addTab("Pedir", PanelEliminar);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cargarComida(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        ArrayList<Comida> comida = DaoComida.getAllRecords();
        Iterator<Comida> itr = comida.iterator();
        while (itr.hasNext()) {
            Comida comidas = itr.next();
            model.addElement(comidas.getComida());
        }
        jComboBoxComida.setModel(model);   
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_formComponentShown

    private void btnSeleComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleComidaActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar la categoria seleccionada?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            String selectedCategory = (String) jComboBoxComida.getSelectedItem();
            DaoComida.eliminar(selectedCategory);
            setVisible(false);
            new AdministrarCategorias().setVisible(true);
        }
    }//GEN-LAST:event_btnSeleComidaActionPerformed

    private void jComboBoxComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxComidaActionPerformed
        // TODO add your handling code here:
        String selectedComida = (String) jComboBoxComida.getSelectedItem();

    }//GEN-LAST:event_jComboBoxComidaActionPerformed

    private void BackgroundComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BackgroundComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_BackgroundComponentShown

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComActionPerformed
        // TODO add your handling code here:
        Comida comida = new Comida();
        comida.setComida(TextoNuevaComida.getText());
        DaoComida.agregar(comida);
        refreshTable();
        setVisible(false);
        new AdministrarCategorias().setVisible(true);
    }//GEN-LAST:event_btnAgregarComActionPerformed

    private void TextoNuevaComidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoNuevaComidaKeyReleased
        // TODO add your handling code here:
        validarCampo();
    }//GEN-LAST:event_TextoNuevaComidaKeyReleased

    private void TextoNuevaComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNuevaComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNuevaComidaActionPerformed

    public void refreshTable(){
        DefaultTableModel dtm = (DefaultTableModel) TablaComida.getModel();
        dtm.setRowCount(0);
        ArrayList<Comida> list = DaoComida.getAllRecords();
        Iterator<Comida> itr = list.iterator();
        while(itr.hasNext()){
            Comida comidaObj = itr.next();
            dtm.addRow(new Object[]{comidaObj.getId(),comidaObj.getComida()});
        }  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarCategorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel LabelAgregar;
    private javax.swing.JLabel LabelEliminar;
    private javax.swing.JLabel LabelTituloCategorias5;
    private javax.swing.JLabel LabelTituloCategoriasAgregar;
    private javax.swing.JPanel PanelAgregarCat;
    private javax.swing.JPanel PanelEliminar;
    private javax.swing.JTable TablaComida;
    private javax.swing.JTextField TextoNuevaComida;
    private javax.swing.JButton btnAgregarCom;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleComida;
    private javax.swing.JComboBox<String> jComboBoxComida;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
